---
title: "Yue Hu's resume"
author: Yue Hu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: True
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> yuehu@tsinghua.edu.cn
- <i class="fa fa-github"></i> [sammo3182](https://github.com/sammo3182)
- <i class="fas fa-globe-asia"></i> [sammo3182.github.io](https://sammo3182.github.io/)
- <i class="fa fa-home"></i> Mingzhai 114, Qinghua Yuan, Haidian District, Beijing 100084, China

Skills 
--------------------------------
- **Analysis & Programming**
- R, Stata, Python, C++, Mathematica, NetLogo, JAGS, UCINET
- **Application**
- LaTeX, Markdown, Git(GitHub)
- **Language**
- English, Chinese (Mandarin)

Professional Affiliation
-----------------------------

Member of American Political Science Association

Member of Midwest Political Science Association

Member of Association of Chinese Political Science

Member of American Association for Chinese Studies


Main
================================================================================

Yue Hu{#title}
--------------------------------------------------------------------------------

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### The University of Iowa

Ph.D. in Political Science

U.S.A

2018-05

### The University of South Carolina

M.A. in Political Science

U.S.A

2013-12

### The University of Regina

M.A. in Political Science

Canada

2011-06

### Nankai University

LL.B. in International Politics

China

2009-06

Additional Training {data-icon=book data-concise=true}
--------------------------------------------------------------------------------
### The University of Iowa

Certificate in Informatics

U.S.A

2016-12

### Experimental Methods

National University of Singapore (IPSA)

Singapore

2014-06/07

Professional Positions {data-icon=suitcase}
-------------------------------------------------------------------------------
### Assistant Professor 

Department of Political Science, Tsinghua University

China

2019-01 - Present

### Deputy Director

Center on Data and Governance of Tsinghua University

China

2019-01 - Present

### Statistical Consultant

Iowa Social Science Research Center, University of Iowa

USA

2015-08 - 2018-05

Peer-Reviewed Journal Articles {data-icon=file}
-------------------------------

### Culture Marker Versus Authority Marker: How Do Language Attitudes Affect Political Trust?

Political Psychology Early View, p. Forthcoming

N/A

2020

Hu, Yue

### The Effects of Foreign Language Proficiency on Public Attitudes: Evidence from the Chinese-Speaking World

Journal of East Asian Studies 20.1

N/A

N/A

**Hu, Yue**, Amy H. Liu

### Are Informal Education Facilities Effective Means for Generating Political Support? A Spatial Analysis

Social Science Quarterly 100.3

N/A

2019

Hu, Yue

### Refocusing Democracy: The Chinese Government’s Framing Strategy in Political Language

Democratization 72.2

N/A

N/A

Hu, Yue

### Tsar Putin and the ‘Corruption’ Thorn in His Side: The Demobilization of Votes in a Competitive Authoritarian Regime

Electoral Studies 54

N/A

2018

Claypool, Vicki Hesli, William Reisinger, Marina Zaloznaya, **Yue Hu**

### Economic Inequality and Class Consciousness

The Journal of Politics 79.3,

N/A

2017

Solt, Frederick, **Yue Hu**, Kevan Hudson, Jungmin Song, et al.

### Economic Inequality and Belief in Meritocracy in the United States

Research & Politics 3.4

N/A

2016

Solt, Frederick, **Yue Hu**, Kevan Hudson, Jungmin Song, et al.

### Aﬀirmative Inaction: Language Education and Labor Mobility among China’s Muslim Minorities

Chinese Sociological Review 48.4

N/A

N/A

Tang, Wenfang, **Yue Hu**, and Shuai Jin

### Institutional Difference and Cultural Difference: A Comparative Study of Canadian and Chinese Cultural Diplomacy

Journal of American-East Asian Relations 20.2-3

N/A

2013

Hu, Yue

Journal Articles in Chinese {data-icon=file}
-------------------

### "Issue-Oriented" vs. "Ism-Oriented": Indigenizing Political Science in China?

《“问题与主义” 导向之争: 西方比较政治学沿革及其借鉴意义》

N/A

2011

胡悦，朱毓朝 《天津社会科学》2011 年第 3 期

### The Cultural Props of Foreign Policy

《对外政策的文化道具:浅析文明冲突论的工具性》

N/A

2010

程同顺,胡悦 《学习论坛》2010 年第 26 期

### An Analysis of Politics Fixed Position of CPPCC from the Political Scientific Angle

《从政治科学角度分析人民政协的政治定位》

N/A

2009

胡悦 《天津市社会主义学院学报》2009 年第 1 期

Software {data-icon=file}
-------------------
### Pewdata: Reproducible Retrieval of Pew Research Center Datasets. Available at The Comprehensive R Archive Network (CRAN)

http://CRAN.R-project.org/package=pewdata.

N/A

2016

Solt, Frederick and **Yue Hu**

### Dotwhisker: Dot-and-Whisker Plots of Regression Results. Available at The Comprehensive R Archive Network

http://CRAN.R-project.org/package=dotwhisker

N/A

2015


Solt, Frederick and **Yue Hu**

### Interplot: Plot the Effects of Variables in Interaction Terms. Available at The Comprehensive R Archive Network

http://CRAN.R-project.org/package=interplot

N/A

2015

Solt, Frederick and **Yue Hu**

Invited Talks {data-icon=comment}
------------------------
### Culture Marker vs. Authority Marker: How Does Language Attitude Affect Political Trust?

N/A

Sun Yat-Sen University, Guangzhou, Jan., 3.

2018

### Investigating Inequality with Real-Life Data: Research Strategies and Methods.

N/A

Nankai University, Tianjin, Jun., 25.

2017

Conferences {data-icon=microphone}
------------------------
### Breaking Through the Linguistic Barrier: The Role of Language Policy in Migration Decisions.

American Political Science Association (APSA) Annual Meeting

Washington D.C., Aug. 29--Sep. 01

2019

### Visualization and Going Against P-Hacking.

China R Conference

Beijing, May 25--26

N/A

### Measuring the Influence of Language in Political Science Research

St. Louis Area Methods Meeting (SLAMM)

Ames, Iowa, Apr. 20

2018

### Rebuilding the Tower of Babel? The Influence of Language Policy on Political Trust

Midwest Political Science Association (MPSA) Annual Convention

Chicago, Illinois, Apr. 5--8

N/A

### Cultural Accent vs. Authority Accent: How Does Language Attitude Affect Political Trust.

:::concise
- Association of Chinese Political Science (ACPS) Annual Meeting, Tianjin, China, Jun., 9--11.
- Chinese Political Science and Methods Workshop, Shanghai, China, Jul., 8--9.
- Political Culture, Psychology, and Behavior Research Workshop, Nanjing, China, Jul., 9--11.
:::

N/A

\ 

2017

### The Weight of History: Explaining the Anti-Japanese Sentiments in the Chinese Circle (with Amy Liu)

Midwest Political Science Association (MPSA) Annual Convention

Chicago, Illinois, Apr. 7--9

N/A

### The Popularity of Political Propaganda in Modern China: A Model of Demands (with Zijie Shao)

Midwest Political Science Association (MPSA) Annual Convention,

Chicago, Illinois, Apr. 7--9

N/A

### The Logic of Peaceful Rise (with Ray Ou-Yang)

:::consice
- Midwest Political Science Association (MPSA) Annual Convention,Chicago, Illinois, Apr. 7--9
- International Studies Association (ISA) Annual Convention,  Baltimore, Maryland, Feb. 22--25
:::

N/A

### Measure Political Desirability: A List Experimental Method(with Wenfang Tang); Propaganda with Museums: A Spatial Analysis of Patriotic Educational Demonstration Bases in China.

Association of Chinese Political Science (ACPS) Annual Meeting

California, Oct, 10--11

2016

### Value Promotion, Justification, or Mobilization? The Dynamic of the Discourse on Democracy in Modern China.

Midwest Political Science Association (MPSA) Annual Conference

Chicago, Apr., 7-10

N/A

### Affirmative Inaction: Education, Social Mobility, and Ethnic Inequality in China (with Wenfang Tang and Shuai Jin); Language and Political Trust.

Midwest Political Science Association (MPSA) Annual Conference

Chicago, Apr., 16--19.

2015

### Connecting Nationalism and Political Transition:A Study of Nationalist Influence on Political Transition based on the China Case

University of South Carolina Inaugural Graduate Student Conference

Columbia, South Carolina

2013

### Twofold-Affecting Model: A Cultural Pattern of Social Change from a Comparative Study between the China and Russia Cases

American Association for Chinese Studies (AACS) Annual Conference

Atlanta, Georgia, Oct. 12-14

2012

Research Program {data-icon=search}
-------
### Youth Project of National Social Science Foundation of China: Assessing and Improving the Political Ecology of Grassroots Party Organizations (ID: 17CZZ041). 

Principal Investigator and Methodology Director

N/A

2017/06 - 2020/06

Teaching Experience {data-icon=chalkboard}
---------
### University of Tsinghua

:::concise
- Analysis of Political Data
- Analysis of Public Policy: Perspectives and Methods
:::

N/A


### University of Iowa

:::concise
- Designing Political Research
- Math Camp for Incoming Graduate Students
- "Hello, R!" Workshop Series
:::

N/A

Grants {data-icon=award}
-------
### Ballard and Seashore Fellowship

N/A

N/A

2017

### Post-Comprehensive Research Award

N/A

N/A

2016

### T. Anne Cleary International Dissertation Research Fellowship

















