---
output: 
  rticles::ctex:
    keep_tex: yes
    template: svm-latex-cv.tex
geometry: margin=1in

chinese: TRUE

title: "教学简历"
author: 胡悦

address: "北京市海淀区清华大学明斋114, 邮编:100084"
fontawesome: yes
email: yue-hu-1@uiowa.edu
web: sammo3182.github.io
updated: false
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10.5pt
linkcolor: blue
urlcolor: blue
photo: verticalYueHu.jpg
---

```{r setup, include=FALSE}
library(RefManageR)
ajps_mimic <- RefManageR:::MakeBibLaTeX()
with(ajps_mimic,{
  ajps_mimic$fmtJournal <- function(s){
                                if (length(s$journaltitle)) {
                                    res <- emph(cleanupLatex(s$journaltitle))
                                    if (length(s$journalsubtitle))
                                        res <- paste(addPeriod(res), emph(cleanupLatex(s$journalsubtitle)))
                                    return(res)
                                }
                                else if (!is.null(s$journal)) {
                                    emph(cleanupLatex(s$journal))
                                }
     }
     
     ajps_mimic$fmtURL <- function (paper) {
        if (length(paper[["url"]])) {
            res <- paper$url
            res <- switch(docstyle, html = paste0("\\url{", 
                res, "}"), markdown = paste0("[", res, "](", 
                res, ")"), paste0("\\url{", res, "}"))
            if (length(paper$urldate)) {
                fDate <- try(ProcessDate(paper$urldate, NULL), TRUE)
                if (!is.null(fDate) && !inherits(fDate, "try-error")) 
                    res <- paste0(res, " (visited on ", DateFormatter(fDate, 
                      TRUE), ")")
            }
            addPeriod(res)
        }
        else if (length(paper$urldate)) {
            fDate <- try(ProcessDate(paper$urldate, NULL), TRUE)
            if (!is.null(fDate) && !inherits(fDate, "try-error")) 
                paste0("(Visited on ", DateFormatter(fDate, TRUE), 
                    ").")
        }
     }
     
     ajps_mimic$fmtLanguage <- function(lang) {
    if (length(lang) && tolower(lang) != "english") 
        paste0("[", sub("\\b(\\w)", "\\U\\1", lang, perl = TRUE, 
            useBytes = TRUE),"]")
       }
     
     ajps_mimic$formatArticle <- function (paper) {
    collapse(c(fmtPrefix(paper), fmtBAuthor(paper), fmtJTitle(paper$title), fmtLanguage(paper$language), 
        fmtAddOn(paper$titleaddon),
        fmtTranslator(paper), fmtCommentator(paper$commentator), 
        fmtAnnotator(paper$annotator), fmtVersion(paper$version), 
        sentenceP(paste0(c(paste0(c(fmtJournal(paper), fmtSeries(paper$series)), 
            collapse = ""), fmtVolume(paper$volume, paper$number), 
            fmtJournDate(paper)), collapse = " "), fmtBTitle(paper$issuetitle, 
            paper$issuesubtitle), fmtEditor(paper, suffix = NULL, 
            prefix = ". "), fmtNote(paper$note, prefix = ". ", 
            suffix = NULL), pgs = fmtPages(paper$pages, paper$pagination), 
            sep = ""),fmtURL(paper), fmtAddendum(paper$addendum), 
        fmtPubstate(paper$pubstate)))
     }
     
     ajps_mimic$formatArticle <- function (paper) {
    collapse(c(fmtPrefix(paper), fmtBAuthor(paper), fmtJTitle(paper$title), fmtLanguage(paper$language), 
        fmtAddOn(paper$titleaddon),
        fmtTranslator(paper), fmtCommentator(paper$commentator), 
        fmtAnnotator(paper$annotator), fmtVersion(paper$version), 
        sentenceP(paste0(c(paste0(c(fmtJournal(paper), fmtSeries(paper$series)), 
            collapse = ""), fmtVolume(paper$volume, paper$number), 
            fmtJournDate(paper)), collapse = " "), fmtBTitle(paper$issuetitle, 
            paper$issuesubtitle), fmtEditor(paper, suffix = NULL, 
            prefix = ". "), fmtNote(paper$note, prefix = ". ", 
            suffix = NULL), pgs = fmtPages(paper$pages, paper$pagination), 
            sep = ""),fmtURL(paper), fmtAddendum(paper$addendum), 
        fmtPubstate(paper$pubstate)))
     }
     
     ajps_mimic$formatUnpublished <- function (paper) {
        collapse(c(fmtPrefix(paper), fmtBAuthor(paper), fmtIBTitle(paper$title, 
            paper$subtitle, FALSE), fmtAddOn(paper$titleaddon), fmtLanguage(paper$language), 
            fmtHowPublished(paper$howpublished), fmtNote(paper$note), 
            sentence(fmtPublisher(NULL, paper$location, paper$address), sep = ""), fmtDOI(paper$doi), 
            fmtURL(paper), fmtAddendum(paper$addendum), fmtPubstate(paper$pubstate)))
     }
     
     ajps_mimic$formatMisc <- function (paper) {
    collapse(c(fmtPrefix(paper), fmtBAuthor(paper), fmtIBTitle(paper$title, 
            paper$subtitle, FALSE), fmtAddOn(paper$titleaddon), fmtLanguage(paper$language), 
        fmtEditor(paper, !length(paper$author)), fmtHowPublished(paper$howpublished), 
        addPeriod(fmtType(paper$type)), fmtVersion(paper$version), 
        fmtNote(paper$note), sentence(fmtPublisher(paper$organization, 
            paper$location, paper$address), fmtDate(attr(paper, 
            "dateobj")), sep = ""), fmtDOI(paper$doi), fmtEprint(paper), 
        fmtURL(paper), fmtAddendum(paper$addendum), fmtPubstate(paper$pubstate)))
}
})


tools::bibstyle("ajps_mimic", ajps_mimic)

bib <- ReadBib("publication.bib", check = FALSE)
BibOptions(check.entries = FALSE, 
           first.inits = FALSE,
           bib.style = "ajps_mimic",
           style = "latex",
           max.names = 4,
           dashed = FALSE,
           sorting = "ydnt")
```


# 教学经历

* 爱荷华大学： 任课教师（政治学研究设计、R语言与社会科学研究系列讲座），教学助理（比较政治学入门等）
* 南卡罗来纳大学：教学助理（国际关系学、争论中的世界政治、比较政治：发展中国家等）
* 里贾纳大学：教学助理（政治学入门）

# 助教详情

## University of Iowa

* Introduction to Political Behavior\hfill Spring 2015
* Introduction to International Relations\hfill Fall 2014
* Introduction to Comparative Politics\hfill Spring 2014
* Political Campaigning\hfill Fall 2014
* Political Psychology\hfill Fall 2014

## University of South Carolina

* International Relations\hfill Spring 2013
* Comparative Politics\hfill Spring 2013
* Controversial World Politics\hfill Fall 2012
* American National Government\hfill Spring 2012
* Comparative Politics-Developing Countries\hfill Spring 2012
* National Security of United States\hfill Fall 2011

## University of Regina

* Introduction to Political Science\hfill Fall 2010


# 教学技能
* 分析与编程: R, Stata, Python, C++, Mathematica, NetLogo, JAGS, UCINET
* 应用:  \LaTeX, Markdown, Git(GitHub)
