---
surname: Yue Hu
position: ""
address: "Mingzhai 114, Qinghua Yuan, Haidian District, Beijing 100084, China"
www: sammo3182.github.io
email: yuehu@tsinghua.edu.cn
github: sammo3182
twitter: yuehupolisci
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "414141"
output: vitae::awesomecv
header-includes:
- \usepackage{ctex}

  
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      encoding = "UTF-8")
source("../script/install.R")

```

```{r get data, include=FALSE}

orcidID<-"0000-0002-2829-3971"

## Education
df_edu <- rorcid::orcid_educations(orcidID)[[orcidID]]$`affiliation-group`$summaries%>%
  rbindlist(fill=T)

### edu_info<-c("education-summary.department-name","education-summary.role-title","education-summary.start-date.year.value","education-summary.end-date.year.value","education-summary.organization.name","education-summary.organization.address.country")



## Qualifications

df_qualifications <- rorcid::orcid_qualifications(orcidID)[[orcidID]]$`affiliation-group`$summaries%>%
  rbindlist(fill=T)

### qualifications_info<-c("qualification-summary.organization.name","qualification-summary.role-title","qualification-summary.end-date.year.value","qualification-summary.end-date.month.value","qualification-summary.organization.address.country")

## jobs
ProfessionalPositions <- orcid_employments(orcidID)[[orcidID]]$`affiliation-group`$summaries

for (i in 1:length(ProfessionalPositions)) {
  if(length(ProfessionalPositions[[i]])==27)
      {ProfessionalPositions[[i]]$`employment-summary.end-date.year.value` <- "Present"
      ProfessionalPositions[[i]]$`employment-summary.end-date.month.value` <- ""}
}

df_position<-rbindlist(ProfessionalPositions,fill = T)


## works
benchmark_orcid <- function(id) {
  tictoc::tic()

  # Get put-codes
  put_codes = orcid_works(id)[[1]] %>%  
    bind_rows() %>% 
    pull(`put-code`)

  # Get info of those put codes
  list_orcid <- orcid_works(id, put_code = put_codes) #%>% bind_rows()
  cat(id, " - ")

  tictoc::toc()

  list_orcid
}

works_raw<-benchmark_orcid(orcidID)[[orcidID]][["works"]]
df_works <-within(works_raw,{
  authors<-NA
  authors <- str_extract(`work.citation.citation-value`,"(?<=author=\\s\\{).*(?=\\}, year)")%>%
    str_replace_all(c("\\{"="","\\}"=""))
})

##membership
df_membership <- orcid_memberships(orcidID)[[orcidID]][["affiliation-group"]][["summaries"]]%>%
  rbindlist(fill=T)
# membership_info <- c("membership-summary.organization.name","membership-summary.organization.address.country")

#Grants

df_grants <- orcid_distinctions(orcidID)[[orcidID]][["affiliation-group"]][["summaries"]]%>%
  rbindlist(fill = T)

```

# Education and Qualifications

*Education*
```{r Education}
df_edu %>%
  detailed_entries(
    with = glue::glue("{`education-summary.role-title`} ({`education-summary.department-name`}) "),
    when = glue::glue("{`education-summary.start-date.year.value`} - {`education-summary.end-date.year.value`}"),
    what = `education-summary.organization.name`,
    where = `education-summary.organization.address.country`
  )
```

*Qualifications*
```{r Qualifications}
df_qualifications%>%
  detailed_entries(
    with = `qualification-summary.role-title`,
    when = glue::glue("{`qualification-summary.end-date.year.value`} - {`qualification-summary.end-date.month.value`}"),
    what = `qualification-summary.organization.name`,
    where = `qualification-summary.organization.address.country`
  )
```

# Professional Positions
```{r ProfessionalPositions}
df_position %>% 
  detailed_entries(
    what = `employment-summary.organization.name`,
    when = glue("{`employment-summary.start-date.year.value`}.{`employment-summary.start-date.month.value`}--{`employment-summary.end-date.year.value`}.{`employment-summary.end-date.month.value`}"),
    with = `employment-summary.role-title`,
    where = `employment-summary.organization.address.country`,)
```

# Publications
**Peer-Reviewed Journal Articles**
```{r PeerReview}
df_works %>%
  filter(work.type=="journal-article")%>%
  arrange(desc(`work.publication-date.year.value`))%>%
  detailed_entries(
    with=`work.title.title.value`,
    what=`work.journal-title.value`,
    when=`work.publication-date.year.value`,
    where=authors
  )

```

**Software**
```{r Software}
df_works %>%
  filter(work.type=="software"|work.type=="other")%>%
  arrange(desc(`work.publication-date.year.value`))%>%
  detailed_entries(
    with =`work.title.title.value`,
    where =`work.journal-title.value`,
    when =`work.publication-date.year.value`,
    what = authors
  )

```

# Conferences
```{r conferences}
df_works %>%
  filter(work.type=="conference-paper")%>%
  arrange(desc(`work.publication-date.year.value`))%>%
  detailed_entries(
    with=`work.title.title.value`,
    what=`work.journal-title.value`,
    when=`work.publication-date.year.value`,
    where=authors 
  )
```


# Grants
```{r grants}
df_grants%>%
  detailed_entries(
    with = `distinction-summary.role-title`,
    what = `distinction-summary.organization.name`,
    when = `distinction-summary.start-date.year.value`,
    )
```


# Professional Affiliation
```{r ProfessionalAffilication}
df_membership%>%
  detailed_entries(
    with = `membership-summary.organization.name`,
    where = `membership-summary.organization.address.country`
  )
```













